import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "One-pc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Переносим NextTopLoader внутрь отдельного client-компонента */}
        <ClientTopLoader />
        {children}
      </body>
    </html>
  );
}

// 🛠 Делаем отдельный client-компонент
function ClientTopLoader() {
  return <NextTopLoader color="#ff0000" height={3} showSpinner={false} />;
}
